### ISSUE TITLE
Julia 1.0 compatability

### ISSUE THREAD

**Issue by mbeach42** [MikeInnes/Traceur.jl#13]
is this going to be made compatible with v0.7/1.0?

**Comment by pfitzseb** [comment]
Yes, I'm on it: https://github.com/MikeInnes/Traceur.jl/pull/11
I'll hopefully have something useable by tomorrow or so.

**Comment by MasonProtter** [comment]
so with #11 merged is this 1.0 compatible now?

**Comment by pfitzseb** [comment]
Yes.
