### ISSUE TITLE
unable to load package

### ISSUE THREAD

**Issue by IgorDouven** [MikeInnes/Traceur.jl#3]
Installation worked fine, but then when I try to load it, `using Traceur`, I get the following error message:

ERROR: LoadError: ArgumentError: Module Vinyl not found in current path.
Run `Pkg.add("Vinyl")` to install the Vinyl package.

Running `Pkg.add("Vinyl")` tells me there is no such package.

**Comment by MikeInnes** [comment]
You must have run `Pkg.clone()` to install, I guess? You just need to run `Pkg.update()`.

**Comment by IgorDouven** [comment]
You're right. Works now -- thanks!

**Comment by MikeInnes** [comment]
Great, let me know if you bump into anything else.
