### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by DilumAluthge** [MikeInnes/Traceur.jl#34]

**Comment by DilumAluthge** [comment]
Bump.

@pfitzseb Any chance you could tag a new release of Traceur.jl? I'd like to use the `nowarn=:all` feature in some other packages.

**Comment by pfitzseb** [comment]
Yeah, but I'd like to fix the tests on 1.2 first.

**Comment by DilumAluthge** [comment]
Sounds good, thanks for the update!
