### ISSUE TITLE
Use min_enabled_level() instead of .min_level ?

### ISSUE THREAD

**Issue by ederag** [MikeInnes/Traceur.jl#47]
The `min_level` property is not part of a logger standard interface (found only as a keyword argument).
Using `.min_level` caused an issue with Pluto custom logger ( https://github.com/fonsp/Pluto.jl/issues/1038).
Perhaps one should use [Logging.min_enabled_level()](https://docs.julialang.org/en/v1/stdlib/Logging/#Logging.min_enabled_level) instead ?

**Comment by c42f** [comment]
Looking at the code in util.jl, the way it's manipulating `global_logger` looks kind of dodgy. I haven't used Traceur, but a better alternative may be a single call to `with_logger()` which wraps the `@trace` entry point.

(In case you're wondering, I arrived here via https://github.com/fonsp/Pluto.jl/issues/1038)

**Comment by ederag** [comment]
@c42f Thanks for the suggestion, is #49 what you had in mind ?
